### ISSUE TITLE
Merge into official AM2R translations

### ISSUE THREAD

**Issue by Miepee** [peachflavored/AM2R-European-Portuguese-Translation#1]
I would love to see this merged into the [official AM2R Updates](https://github.com/AM2R-Community-Developers/AM2R-Localizations)!
A few question regarding the translations though:
- Did you already have a second source reading through this and proof-read for any mistakes or inconsistencies? I saw that [someone on reddit](https://www.reddit.com/r/AM2R/comments/i8y48s/am2r_european_portuguese_ptpt_translation/g249sb0?utm_source=share&utm_medium=web2x&context=3) made a few comments regarding the translation, but not sure if you actually used their efforts or not. @LiveLM may also be able to help a bit with proof-reading. He is brazilian, but it should still help.
- Would you be ok, if this would be used as a base for a portuguese brazilian translation? (And also proof read that one, to the best of your abilities?)
- Would you like to work with the one reddit user, as well as LiveLM in order to create a universal portuguese language for the [AM2RLauncher](https://github.com/AM2R-Community-Developers/AM2RLauncher)?

**Comment by peachflavored** [comment]
Regarding your questions, I've proof-read it several times during all versions and the latest version was also tested by Katherine_S2003 (which is also a Portuguese native like me) on Reddit that pointed out a small mistake which was promptly corrected back then.

You may use my translation as a base for a Brazilian Portuguese translation but to my knowledge there were a few already available back in the day made by a group of several people. Don't know if the quality of those translations is good or not, since there are always a few terms that differ between both languages even if they're the same (some words used in Brazilian Portuguese might sound off for Portuguese native people). Also I opted for not translating some technical game terms since they sound way bad in Portuguese.

So as far as I am concerned, I rather see two different Portuguese language translations than an universal one for this matter alone.

**Comment by Miepee** [comment]
Good to hear it has been proof read at least. Don't worry about not translating technical game terms, a few languages do that.

Regarding the brazilian translation, I'd rather have it based on yours, since that would mean that brazilian and portugal portuguese would be fairly similar, and not completely different.

Regarding a unified portuguese translation, that would ***only*** be for the AM2RLauncher, not AM2R itself. As you already said, portugal and brazilian differ to much in the words, which would it really difficult for AM2R itself with how many logs there are. AM2RLauncher though has not a lot of text, on average only one sentence, which why I think it's possible to pull one off there.

**Comment by peachflavored** [comment]
Oh, for the AM2R Launcher is fine by me and makes perfect sense being unified as a single language. I'm sure that some more people have played the game using my translation since I've been sharing it over Facebook for quite sometime, mostly Brazilian people but no one ever gave me feedback on the work except for Katherine_S2003 on Reddit.
